 name: ✨ Feature Request
description: Suggest a new feature or enhancement for RE:MIND
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand and prioritize your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point are you experiencing?
      placeholder: Describe the problem or limitation you're facing...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution or feature
      placeholder: Describe how you'd like this to work...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or workarounds you've considered
      placeholder: What other approaches have you tried or considered?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocks my workflow
        - High - Would significantly improve my experience
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - UI/UX Improvement
        - New Functionality
        - Performance Enhancement
        - Accessibility
        - Integration (Calendar, Email, etc.)
        - Mobile App Feature
        - PWA Enhancement
        - API Enhancement
        - Other
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe this from a user's perspective
      placeholder: "As a [type of user], I want [goal] so that [benefit]"
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What specific requirements must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: If you have any mockups, wireframes, or design ideas, please share them
      placeholder: Drag and drop images here or paste URLs

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Considerations
      description: Any technical notes, constraints, or implementation ideas
      placeholder: Database changes needed, API endpoints, performance considerations, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all required information above
          required: true
        - label: This feature aligns with RE:MIND's mission of being a fast, easy-to-use reminder app
          required: true